package Ljc.JFramework.Net;

import java.io.IOException;
import java.net.HttpURLConnection;

import Ljc.JFramework.Utility.StringUtil;

public class HttpResponseEx {
	private boolean _cacheControl = false;

	// Summary:
	// The Cache-Control header, which specifies caching directives that must be
	// obeyed by all caching mechanisms along the request/response chain.
	public boolean getCacheControl() {
		return this._cacheControl;
	}

	public void setCacheControl(boolean value) {
		this._cacheControl = value;
	}

	public String Connection;
	//
	// Summary:
	// The Date header, which specifies the date and time at which the response
	// originated.
	public String Date;
	//
	// Summary:
	// The Keep-Alive header, which specifies a parameter to be used to maintain
	// a persistent connection.
	public String KeepAlive;
	//
	// Summary:
	// The Pragma header, which specifies implementation-specific directives that
	// might apply to any agent along the request/response chain.
	public String Pragma;
	//
	// Summary:
	// The Trailer header, which specifies that the indicated header fields are
	// present in the trailer of a message that is encoded with chunked
	// transfer-coding.
	public String Trailer;
	//
	// Summary:
	// The Transfer-Encoding header, which specifies what (if any) type of
	// transformation
	// has been applied to the message body.
	public String TransferEncoding;
	//
	// Summary:
	// The Upgrade header, which specifies additional communications protocols that
	// the client supports.
	public String Upgrade;
	//
	// Summary:
	// The Via header, which specifies intermediate protocols to be used by gateway
	// and proxy agents.
	public String Via;
	//
	// Summary:
	// The Warning header, which specifies additional information about that status
	// or transformation of a message that might not be reflected in the message.
	public String Warning;
	//
	// Summary:
	// The Allow header, which specifies the set of HTTP methods that are supported.
	public String Allow;
	//
	// Summary:
	// The Content-Length header, which specifies the length, in bytes, of the
	// accompanying
	// body data.
	public String ContentLength;
	//
	// Summary:
	// The Content-Type header, which specifies the MIME type of the accompanying
	// body data.
	public String ContentType;
	//
	// Summary:
	// The Content-Encoding header, which specifies the encodings that have been
	// applied to the accompanying body data.
	public String ContentEncoding;
	//
	// Summary:
	// The Content-Langauge header, which specifies the natural language or
	// languages
	// of the accompanying body data.
	public String ContentLanguage;
	//
	// Summary:
	// The Content-Location header, which specifies a URI from which the
	// accompanying
	// body can be obtained.
	public String ContentLocation;
	//
	// Summary:
	// The Content-MD5 header, which specifies the MD5 digest of the accompanying
	// body data, for the purpose of providing an end-to-end message integrity
	// check.
	public String ContentMd5;
	//
	// Summary:
	// The Range header, which specifies the subrange or subranges of the response
	// that the client requests be returned in lieu of the entire response.
	public String ContentRange;
	//
	// Summary:
	// The Expires header, which specifies the date and time after which the
	// accompanying
	// body data should be considered stale.
	public String Expires;
	//
	// Summary:
	// The Last-Modified header, which specifies the date and time at which the
	// accompanying body data was last modified.
	public String LastModified;
	//
	// Summary:
	// The Accept-Ranges header, which specifies the range that is accepted by the
	// server.
	public String AcceptRanges;
	//
	// Summary:
	// The Age header, which specifies the time, in seconds, since the response
	// was generated by the originating server.
	public String Age;
	//
	// Summary:
	// The Etag header, which specifies the current value for the requested variant.
	public String ETag;
	//
	// Summary:
	// The Location header, which specifies a URI to which the client is redirected
	// to obtain the requested resource.
	public String Location;
	//
	// Summary:
	// The Proxy-Authenticate header, which specifies that the client must
	// authenticate
	// itself to a proxy.
	public String ProxyAuthenticate;
	//
	// Summary:
	// The Retry-After header, which specifies a time (in seconds), or a date and
	// time, after which the client can retry its request.
	public String RetryAfter;
	//
	// Summary:
	// The Server header, which specifies information about the originating server
	// agent.
	public String Server;
	//
	// Summary:
	// The Set-Cookie header, which specifies cookie data that is presented to the
	// client.
	public String SetCookie;
	//
	// Summary:
	// The Vary header, which specifies the request headers that are used to
	// determine
	// whether a cached response is fresh.
	public String Vary;
	//
	// Summary:
	// The WWW-Authenticate header, which specifies that the client must
	// authenticate
	// itself to the server.
	public String WwwAuthenticate;

	private byte[] _responseBytes;

	public byte[] getResponseBytes() {
		return this._responseBytes;
	}

	public void setResponseBytes(byte[] value) {
		this._responseBytes = value;
	}

	private String _characterSet = "utf-8";

	public String getCharacterSet() {
		return this._characterSet;
	}

	public void setCharacterSet(String value) {
		this._characterSet = value;
	}

	private String _responseContent;

	/// <summary>
	/// 请求返回内容
	/// </summary>
	public String getResponseContent() {

		return _responseContent;

	}

	public void setResponseContent(String value) {

		_responseContent = value;

	}

	private static String GetHeaderValue(WebHeaderCollection header, String name) {
		if (header == null)
			return "";
		return header.get(name);

	}

	private boolean _successed = false;

	public boolean getSuccessed() {
		return _successed;
	}

	public void setSuccessed(boolean value) {
		_successed = value;
		if (value) {
			_errorMsg = null;
		}
	}

	private Exception _errorMsg = new Exception();

	/// <summary>
	/// 错误信息
	/// </summary>
	public Exception getErrorMsg() {
		return _errorMsg;
	}

	void setErrorMsg(Exception value) {
		_errorMsg = value;
	}

	private String _responseUrl;

	public String getResponseUrl() {
		return this._responseUrl;
	}

	public void setResponseUrl(String value) {
		this._responseUrl = value;
	}

	private int _statusCode;

	public int getStatusCode() {
		return this._statusCode;
	}

	public void setStatusCode(int value) {
		this._statusCode = value;
	}

	private String _statusDescription;

	public String getStatusDescription() {
		return this._statusDescription;
	}

	private long _requestMills;

	public long getRequestMills() {
		return this._requestMills;
	}

	public HttpResponseEx PraseHeader(HttpURLConnection httpWebResponse) throws IOException {

		if (httpWebResponse != null) {
			this.AcceptRanges = httpWebResponse.getHeaderField("AcceptRanges");
			this.Age = httpWebResponse.getHeaderField("Age");
			this.Allow = httpWebResponse.getHeaderField("Allow");
			this.Connection = httpWebResponse.getHeaderField("Connection");
			this.ContentEncoding = httpWebResponse.getHeaderField("Content-Encoding");
			this.ContentLanguage = httpWebResponse.getHeaderField("Content-Language");
			this.ContentLength = httpWebResponse.getHeaderField("Content-Length");
			this.ContentLocation = httpWebResponse.getHeaderField("Content-Location");
			this.ContentMd5 = httpWebResponse.getHeaderField("ContentMd5");
			this.ContentRange = httpWebResponse.getHeaderField("Content-Range");
			this.ContentType = httpWebResponse.getHeaderField("Content-Type");
			System.out.println(ContentType);
			if (!StringUtil.isNullOrEmpty(this.ContentType)) {
				String[] charsets = this.ContentType.split("charset=");
				if (charsets.length > 0) {
					this._characterSet = charsets[charsets.length - 1].split(";")[0];
				}
			}

			this.Date = httpWebResponse.getHeaderField("Date");
			this.ETag = httpWebResponse.getHeaderField("ETag");
			this.Expires = httpWebResponse.getHeaderField("Expires");
			this.KeepAlive = httpWebResponse.getHeaderField("KeepAlive");
			this.LastModified = httpWebResponse.getHeaderField("LastModified");
			this.Location = httpWebResponse.getHeaderField("Location");
			this.Pragma = httpWebResponse.getHeaderField("Pragma");
			this.ProxyAuthenticate = httpWebResponse.getHeaderField("ProxyAuthenticate");
			this.RetryAfter = httpWebResponse.getHeaderField("RetryAfter");
			this.Server = httpWebResponse.getHeaderField("Server");
			this.SetCookie = httpWebResponse.getHeaderField("Set-Cookie");
			System.out.println("cookie" + this.SetCookie);
			this.Trailer = httpWebResponse.getHeaderField("Trailer");
			this.TransferEncoding = httpWebResponse.getHeaderField("Transfer-Encoding");
			this.Upgrade = httpWebResponse.getHeaderField("Upgrade");
			this.Vary = httpWebResponse.getHeaderField("Vary");
			this.Via = httpWebResponse.getHeaderField("Via");
			this.Warning = httpWebResponse.getHeaderField("Warning");
			this.WwwAuthenticate = httpWebResponse.getHeaderField("WwwAuthenticate");
			this._statusCode = (int) httpWebResponse.getResponseCode();
			this._statusDescription = httpWebResponse.getResponseMessage();
			System.out.println(this._statusDescription);
			this._responseUrl = httpWebResponse.getURL().getPath();
		}
		return this;
	}
}
